FROM mini-baseos:24.04

RUN chmod 644 /etc/shadow
RUN apt-get update && apt-get remove -y curl && rm -rf /var/lib/apt/lists/*
RUN ln -snf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && echo "Asia/Tokyo" > /etc/timezone